package com.aetherinsight.work_managers

object Constants {
    const val NOTIFICATION_TITLE_KEY = "NOTIFICATION_TITLE_KEY"
    const val NOTIFICATION_CONTENT_KEY = "NOTIFICATION_CONTENT_KEY"
    const val NOTIFICATION_TIMEOUT = "NOTIFICATION_TIMEOUT"
    const val NOTIFICATION_TAG = "MOVIE_NOTIFICATION_TAG"
    const val EARLY_NOTIFICATION_TAG = "EARLY_MOVIE_NOTIFICATION_TAG"
    const val ACTION_TAG = "ACTION_MOVIE_TAG"
    const val ACTION_CONTENT_DATA = "ACTION_CONTENT_DATA"
}