name: Run Unit Tests

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v3.4.2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Test
        run: |
          ./gradlew testDebugUnit
          
