name: Debug Build and Deploy

on:
  push:
    branches:
      - develop


jobs:
  build:
    name: Deploy Debug
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    permissions:
      contents: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Adding git config to push tag
        run: |
          git config --global user.email "ruliam.oliveira@gmail.com"
          git config --global user.name "Ruliam Oliveira"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3

      - name: Add current platform to Bundler lockfile
        run: |
          bundle lock --add-platform ruby
          bundle lock --add-platform x86_64-linux

      - name: Install Gems
        run: bundle install

      - name: Make gradlew executable
        run: chmod +x ./gradlew

#      - name: Build and Deploy Debug
#        run: bundle exec fastlane build_debug
#        env:
#          DEBUG_API_KEY: ${{ secrets.DEBUG_API_KEY }}
#          GITHUB_RUNNER_NUMBER: ${{ github.run_number }}
      - name: Testing tags
        run: bundle exec fastlane run analyze_commits match:"debug/*"
