name: Release Build and Deploy

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > keystore.jks

      - name: Decode Play Services Json
        env:
          ENCODED_STRING: ${{ secrets.PLAY_SERVICES_RELEASE }}
        run: |
          echo $ENCODED_STRING > play_services-b64.txt
          base64 -d play_services-b64.txt > app/google-services.json

      - name: Run Fastlane Deploy
        run: bundle exec fastlane build_release
        env:
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
